---
version: 0.2

branches:
  default:
    stage: pre-merge
models:
    - env: &global_env
         CIRCLE_NODE_TOTAL: "4"
         ENABLE_LOCAL_CACHE: "1"
         CIRCLE_ARTIFACTS: '/tmp'
         REPORT_TOKEN: report-token-1
    - Git: &clone
       name: Pull repo
       repourl: '%(prop:git_reference)s'
       shallow: True
       retryFetch: True
       haltOnFailure: True
       # Machine Setup
    - ShellCommand: &update_hosts
       name: Update hosts
       command: 
              sudo bash -c "echo '127.0.0.1       bucketwebsitetester.s3-website-us-east-1.amazonaws.com
                         ' >> /etc/hosts"
       haltOnFailure: True

stages:
  pre-merge:
    worker: &master-worker
         type: docker
         path: eve/workers/build
         volumes: &default_volumes
           - '/home/eve/workspace'
    steps:
       - TriggerStages:
           name: Launch all nodes simultaneously
           stage_names:
             - node0
           #  - node1
           #  - node2
           #  - node3
           waitForFinish: True
           haltOnFailure: True
  node0:
    worker: *master-worker
    steps:
       - Git: *clone
       - ShellCommand: *update_hosts
       - ShellCommand:
           command: rm -rf node_modules
       - ShellCommand:
           command: npm install
       - ShellCommandWithSecrets:
           name: Node 1 Tests
           command: bash tests.bash
           env:
              <<: *global_env
              CIRCLE_NODE_INDEX: "0"
           haltOnFailure: True
  node1:
    worker: *master-worker
    steps:
       - Git: *clone
  node2:
    worker: *master-worker
    steps:
       - Git: *clone
  node3:
    worker: *master-worker
    steps:
       - Git: *clone
       - ShellCommand: *update_hosts

